TRAIN:
  BATCH_SIZE : 60
  Stage1_MAX_EPOCH : 100
  Stage2_MAX_EPOCH: 50
  SEED : 5
  LR : 2e-4
  WEIGHT_DECAY : 1e-4
  MASK_PROBABILITY : 0.15
  PR_PATH : "pr_f_1280_2000.pkl"
  DICT_SIZE : 8
  PR_CONFOUNDER_PATH : "pr_confoudner.pkl"
  SAVE_MODEL : True
  SAVE_LAST_EPOCH : True
  OUTPUT_DIR : "your_dir_name"

